#!/usr/bin/env bun
// Generates src/workflow/embedded.generated.ts from agent-definitions/ so
// compiled binaries can materialize skills + extensions on first run. Run from
// build.ts (and committed so dev/test source runs have the current snapshot).
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dir, '..');
const defDir = path.resolve(root, '..', 'agent-definitions');
const out = path.join(root, 'src', 'workflow', 'embedded.generated.ts');

const files: Record<string, string> = {};
const walk = (dir: string, prefix: string) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, `${prefix}${entry.name}/`);
    else if ((entry.name.endsWith('.md') || entry.name.endsWith('.ts')) && !entry.name.startsWith('.')) {
      files[`${prefix}${entry.name}`] = fs.readFileSync(full, 'utf8');
    }
  }
};
walk(path.join(defDir, 'skills'), 'skills/');
walk(path.join(defDir, 'extensions'), 'extensions/');

const hash = createHash('sha1').update(Object.entries(files).sort().map(([k, v]) => `${k}\u0000${v}`).join('\u0001')).digest('hex').slice(0, 12);
const version = `sha1-${hash}`;

const body = `// AUTO-GENERATED by scripts/generate-embedded.ts — do not edit.
// Bundles agent-definitions (role skills + extensions) for first-run
// materialization in compiled binaries. Regenerate after changing
// agent-definitions: bun run scripts/generate-embedded.ts
export const AGENT_DEFINITION_VERSION = ${JSON.stringify(version)};
export const AGENT_DEFINITIONS: Record<string, string> = ${JSON.stringify(files, null, 2)};
`;
fs.writeFileSync(out, body);
console.log(`embedded ${Object.keys(files).length} files (${version}) -> ${path.relative(root, out)}`);
