#!/usr/bin/env bun
// Generates src/workflow/embedded.generated.ts from runtime-neutral instructions
// and explicitly injected telemetry bridges.
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dir, "..");
const defDir = path.resolve(root, "..", "agent-definitions");
const out = path.join(root, "src", "workflow", "embedded.generated.ts");

const files: Record<string, string> = {};
const walk = (dir: string, prefix: string) => {
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) walk(full, `${prefix}${entry.name}/`);
		else if (
			(entry.name.endsWith(".md") ||
				entry.name.endsWith(".ts") ||
				entry.name.endsWith(".js")) &&
			!entry.name.startsWith(".")
		) {
			files[`${prefix}${entry.name}`] = fs.readFileSync(full, "utf8");
		}
	}
};
walk(path.join(defDir, "instructions"), "instructions/");
walk(path.join(defDir, "bridges"), "bridges/");

const hash = createHash("sha1")
	.update(
		Object.entries(files)
			.sort()
			.map(([k, v]) => `${k}\u0000${v}`)
			.join("\u0001"),
	)
	.digest("hex")
	.slice(0, 12);
const version = `sha1-${hash}`;

const body = `// AUTO-GENERATED by scripts/generate-embedded.ts — do not edit.
// Bundles runtime-neutral instructions and explicitly injected telemetry bridges.
// Regenerate after changing agent-definitions: bun run scripts/generate-embedded.ts
export const AGENT_DEFINITION_VERSION = ${JSON.stringify(version)};
export const AGENT_DEFINITIONS: Record<string, string> = ${JSON.stringify(files, null, 2)};
`;
fs.writeFileSync(out, body);
console.log(
	`embedded ${Object.keys(files).length} files (${version}) -> ${path.relative(root, out)}`,
);
