// Target-driven definition compilation (`port-action-execution-to-bun`,
// task 1.3).
//
// `test/fixtures/actions/targets.json` is generated by
// `server/pkg/actionregistry/target_fixtures_test.go`: it materializes a real
// recipe tree (compose file, Dockerfile, chart, shell scripts), records every
// path as `{{ROOT}}`, and stores the definitions Go compiled for each scenario.
// The test rebuilds the same tree in its own temporary root and replays each
// scenario, so the compose leaf, dependency recursion, readiness gate,
// failure-only diagnostics, port forwards, secret handling and the Docker
// build/artifact pipeline are all compared field by field.
import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type { ActionDefinition } from "@devenv/types";
import {
	compileContainerTargets,
	compileContainerTargetsWithTools,
	compileTargetGraph,
	type DependencyResolver,
} from "../src/server/actions/target-compile.ts";
import type {
	ActionTarget,
	DependencyRef,
	ToolSet,
} from "../src/server/actions/targets.ts";

interface ResolverEntry {
	refKey: string;
	appIdent: string;
	targetIndex: number;
}
interface TargetGroup {
	name: string;
	mode: "graph" | "container-all-tools" | "container-limited";
	target: ActionTarget;
	actions: ActionDefinition[];
}
interface TargetFixture {
	targets: ActionTarget[];
	resolver: ResolverEntry[];
	groups: TargetGroup[];
}

/** The recipe tree the fixture was captured against, recreated per test run. */
const RECIPE_FILES: Record<string, string> = {
	"apps/api/docker-compose.yml": "services: {}\n",
	"apps/api/Dockerfile": "FROM scratch\n",
	"apps/api/chart/Chart.yaml": "name: api\n",
	"apps/api/run.sh": "#!/bin/sh\ntrue\n",
	"apps/api/task.ps1": "exit 0\n",
	"infra/postgres/docker-compose.yml": "services: {}\n",
};

const ALL_TOOLS: ToolSet = {
	docker: true,
	podman: true,
	dockerCompose: true,
	podmanCompose: true,
	tmux: true,
	kind: true,
	kubectl: true,
	helm: true,
};
const LIMITED_TOOLS: ToolSet = {
	docker: true,
	dockerCompose: true,
	tmux: true,
};

function createLayout(): string {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "devenv-action-fixture-"));
	fs.mkdirSync(path.join(root, "home", ".config", "devenv"), {
		recursive: true,
	});
	fs.mkdirSync(path.join(root, "tmp"), { recursive: true });
	for (const [relative, content] of Object.entries(RECIPE_FILES)) {
		const full = path.join(root, relative);
		fs.mkdirSync(path.dirname(full), { recursive: true });
		fs.writeFileSync(full, content);
	}
	return root;
}

const root = createLayout();
const raw = fs.readFileSync(
	path.join(import.meta.dir, "fixtures", "actions", "targets.json"),
	"utf8",
);
const materialized = raw.replaceAll("{{ROOT}}", root);
const fixture: TargetFixture = JSON.parse(materialized);

/** Go emits `"inputs": null` where the port carries an empty array. */
function normalize(value: unknown): unknown {
	return JSON.parse(
		JSON.stringify(value).replaceAll('"inputs":null', '"inputs":[]'),
	);
}

/** Mirrors `fixtureRefKey` in the Go generator. */
function refKey(ref: DependencyRef): string {
	return JSON.stringify([
		ref.app ?? "",
		ref.infra ?? "",
		ref.runtime ?? "",
		ref.profile ?? "",
		ref.provider ?? "",
	]);
}

const resolverByKey = new Map(
	fixture.resolver.map((entry) => [entry.refKey, entry]),
);

const resolver: DependencyResolver = (ref) => {
	const entry = resolverByKey.get(refKey(ref));
	if (!entry) return undefined;
	const target = fixture.targets[entry.targetIndex];
	if (!target) return undefined;
	return { appIdent: entry.appIdent, target };
};

// The compiler takes what production reads from the environment
// (`DEVENV_CONFIG_DIR`, `TMPDIR`) and the checkout directory as parameters.
const PATHS = {
	checkoutDir: path.join(root, "apps", "api"),
	configDir: path.join(root, "home", ".config", "devenv"),
	tempDir: path.join(root, "tmp"),
};

function compile(group: TargetGroup): ActionDefinition[] {
	const ident = group.target.id.split("/")[1] ?? "";
	switch (group.mode) {
		case "graph":
			return [
				compileTargetGraph(
					ident,
					group.target,
					resolver,
					PATHS.checkoutDir,
					{
						composeCommand: "docker-compose",
						runtimeCommand: "docker",
					},
					PATHS,
				),
			];
		case "container-all-tools":
			return compileContainerTargetsWithTools(
				ident,
				group.target,
				resolver,
				ALL_TOOLS,
				PATHS,
			);
		case "container-limited":
			return compileContainerTargetsWithTools(
				ident,
				group.target,
				resolver,
				LIMITED_TOOLS,
				PATHS,
			);
	}
}

function group(name: string): TargetGroup {
	const found = fixture.groups.find((g) => g.name === name);
	if (!found) throw new Error(`missing fixture group ${name}`);
	return found;
}

describe("target-driven compilation", () => {
	for (const scenario of fixture.groups) {
		test(`${scenario.name} matches the definition Go produced`, () => {
			expect(normalize(compile(scenario))).toEqual(normalize(scenario.actions));
		});
	}

	test("every captured scenario is exercised", () => {
		expect(fixture.groups.length).toBeGreaterThan(8);
		expect(new Set(fixture.groups.map((g) => g.mode))).toEqual(
			new Set(["graph", "container-all-tools", "container-limited"]),
		);
	});
});

describe("tool availability decides which variants exist", () => {
	test("docker, compose, podman and tmux each gate their own variant", () => {
		const dockerRun = group("docker-run-all-tools");
		expect(fixture.groups.map((g) => g.name)).toContain(
			"docker-run-limited-tools",
		);
		// docker absent, podman-compose present: the podman variant survives.
		const withoutDocker = compileContainerTargetsWithTools(
			"api",
			dockerRun.target,
			resolver,
			{ podman: true, podmanCompose: true },
			PATHS,
		);
		expect(withoutDocker.map((a) => a.runtime)).toEqual(["podman"]);

		// Neither provider: nothing to run the compose file with.
		const withoutAnyProvider = compileContainerTargetsWithTools(
			"api",
			dockerRun.target,
			resolver,
			{ tmux: true },
			PATHS,
		);
		expect(withoutAnyProvider).toEqual([]);

		const withoutTmux = compileContainerTargetsWithTools(
			"api",
			group("shell-run-all-tools").target,
			resolver,
			{ docker: true, dockerCompose: true },
			PATHS,
		);
		expect(withoutTmux.map((a) => a.runtime)).toEqual(["command-shell"]);
	});

	test("a missing kind/kubectl/helm removes the kubernetes variant", () => {
		const kubernetes = compileContainerTargetsWithTools(
			"api",
			group("kubernetes-run-all-tools").target,
			resolver,
			{ docker: true, kind: true, kubectl: true },
			PATHS,
		);
		expect(kubernetes).toEqual([]);
	});

	test("without an explicit tool set every variant is produced", () => {
		const all = compileContainerTargets(
			"api",
			group("shell-run-all-tools").target,
			resolver,
			PATHS,
		);
		expect(all.map((a) => a.runtime)).toEqual(["tmux", "command-shell"]);
	});
});

describe("availability follows the source path", () => {
	test("a missing source is unavailable with the Go diagnostic", () => {
		const [definition] = group("missing-source-graph").actions;
		if (!definition) throw new Error("no action");
		expect(definition.availability).toEqual({
			available: false,
			reason: `required source unavailable: ${path.join(root, "apps", "missing", "docker-compose.yml")}`,
		});
	});

	test("an existing source is available", () => {
		const [definition] = group("docker-run-all-tools").actions;
		expect(definition?.availability).toEqual({ available: true });
	});

	test("an empty source path never becomes unavailable", () => {
		const definition = compileTargetGraph("api", {
			id: "app/api/run/shell",
			action: "run",
			runtime: "shell",
			label: "Run",
			sourcePath: "",
		});
		expect(definition.availability).toEqual({ available: true });
	});

	test("the source probe is injectable instead of reading the disk", () => {
		const target: ActionTarget = {
			id: "app/api/run/docker",
			action: "run",
			runtime: "docker",
			label: "Run",
			sourcePath: "/nowhere/docker-compose.yml",
		};
		expect(
			compileTargetGraph("api", target, undefined, "", undefined, {
				sourceExists: () => true,
			}).availability,
		).toEqual({ available: true });
		expect(compileTargetGraph("api", target).availability).toEqual({
			available: false,
			reason: "required source unavailable: /nowhere/docker-compose.yml",
		});
	});
});

describe("dependency steps", () => {
	const run = group("docker-run-all-tools");

	test("a resolvable dependency gets its own execution subtree", () => {
		const [action] = run.actions;
		if (!action) throw new Error("no action");
		const dependency = action.root.children?.[0];
		expect(dependency?.kind).toBe("composite");
		expect(dependency?.executionKey).toBe("dependency/db/docker/default");
		expect(dependency?.children?.map((c) => c.kind)).toEqual([
			"command",
			"readiness",
		]);
	});

	test("an unresolvable dependency keeps a start step and a readiness gate", () => {
		const [action] = group("dependency-outcomes-all-tools").actions;
		if (!action) throw new Error("no action");
		const [cache] = action.root.children ?? [];
		expect(cache?.children?.map((c) => c.kind)).toEqual([
			"operation",
			"readiness",
		]);
		expect(cache?.children?.[0]?.configuration?.dependency).toEqual({
			infra: "cache",
		});
	});

	test("an external dependency never gets a start step", () => {
		const [action] = group("dependency-outcomes-all-tools").actions;
		if (!action) throw new Error("no action");
		const external = action.root.children?.[1];
		expect(external?.children?.map((c) => c.kind)).toEqual(["readiness"]);
		expect(external?.configuration?.lifecycle).toBe("external");
	});

	test("only a run target compiles dependency steps", () => {
		// A build or test target replaces its children with the build pipeline,
		// so a declared dependency never becomes a step there.
		for (const name of ["docker-build-all-tools", "docker-test-all-tools"]) {
			const [action] = group(name).actions;
			const ids = (action?.root.children ?? []).map((c) => c.id);
			expect(ids.some((id) => id.includes("/step/dependency/"))).toBe(false);
		}
	});
});
