// Action-target discovery (`port-action-execution-to-bun`, task 4.2).
//
// `test/fixtures/actions/discovery.json` is generated by
// `server/pkg/resources/discovery_fixtures_test.go` from a materialized
// configured environment (compose files, shell action scripts with a
// `# devenv:` header, a checkout with every supported build tool, Helm charts).
// Every path is a `{{ROOT}}` recipe key, so the test rebuilds the same tree and
// compares the discovered targets field by field.
import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
	applyKubernetesIdentity,
	defaultKubernetesRelease,
	discoverActionTargets,
	discoverHelmCharts,
	expandKubernetesPath,
	kubernetesProfileForChart,
	packageManagerCommand,
	parseComposeRequires,
	parseDependencyRefs,
	parseShellScriptMetadata,
} from "../src/server/actions/discovery.ts";
import type { ActionTarget } from "../src/server/actions/targets.ts";

interface FixtureTarget {
	id: string;
	action: string;
	runtime: string;
	label: string;
	profile?: string;
	provider?: string;
	launchMode?: string;
	sourcePath: string;
	command?: string;
	args?: string[];
	requires?: unknown[];
	kubernetes?: Record<string, unknown>;
}
interface DiscoveryCase {
	name: string;
	appIdent: string;
	action: "build" | "test" | "run";
	localDir: string;
	targets: FixtureTarget[];
}
interface DiscoveryFixture {
	cases: DiscoveryCase[];
}

const RECIPE: Record<string, { content: string; mode?: number }> = {
	"config/apps/build/shop-build.Dockerfile": { content: "FROM scratch\n" },
	"config/apps/build/shop-build.sh": {
		content:
			"# devenv:name=Custom build\n# devenv:mode=tmux\n#!/bin/sh\necho build\n",
		mode: 0o755,
	},
	"config/apps/build/shop-test.sh": {
		content: "#!/bin/sh\necho test\n",
		mode: 0o755,
	},
	"config/apps/build/shop-build.ps1": {
		content: "# devenv:name=PS build\nWrite-Host build\n",
		mode: 0o755,
	},
	"config/apps/build/api-test.sh": { content: "#!/bin/sh\necho api test\n" },
	"config/apps/compose/shop-compose.yml": { content: "services: {}\n" },
	"config/apps/compose/shop-compose.yaml": { content: "services: {}\n" },
	"config/apps/compose/shop-edge-compose.yml": {
		content:
			'x-devenv:\n  requires: [{"infra":"postgres","runtime":"kubernetes","profile":"local"}]\nservices: {}\n',
	},
	"config/apps/compose/other-compose.yml": { content: "services: {}\n" },
	"config/apps/run/shop-dev.sh": {
		content:
			'# devenv:name=Dev server\n# devenv:mode=tmux\n# devenv:requires=[{"app":"db","runtime":"docker","profile":"default"}]\n#!/bin/sh\n',
	},
	"config/apps/run/shop-dev.ps1": { content: "#!/usr/bin/env pwsh\n" },
	"config/apps/run/shop-api.sh": { content: "#!/bin/sh\n" },
	"config/apps/run/other-dev.sh": { content: "#!/bin/sh\n" },
	"config/apps/k8s/shop/chart/Chart.yaml": { content: "name: shop\n" },
	"config/apps/k8s/api/devenv.k8s.json": {
		content: JSON.stringify({
			targets: [
				{
					profile: "staging",
					provider: "podman",
					cluster: "shop-cluster",
					chart: {
						path: "$APP/helm",
						values: ["$CONFIG/apps/k8s/api/values.yaml"],
					},
					release: "custom",
					namespace: "apps",
					secrets: [{ name: "env", keys: ["DB_PASS"] }],
					image: {
						repository: "shop-api",
						tag: "latest",
						pullPolicy: "Never",
						valuePaths: {
							repository: "image.repository",
							tag: "image.tag",
							pullPolicy: "image.pullPolicy",
						},
					},
					ports: [
						{
							name: "web",
							resource: "service/api",
							localPort: 8080,
							remotePort: 80,
						},
					],
					wait: { timeout: "5m" },
					requires: [
						{ infra: "postgres", runtime: "kubernetes", profile: "local" },
					],
				},
			],
		}),
	},
	"checkout/Makefile": { content: "build:\n\ttrue\n\ntest:\n\ttrue\n" },
	"checkout/justfile": { content: "build:\n\ttrue\n" },
	"checkout/Taskfile.yml": { content: "tasks:\n  build:\n    cmds: []\n" },
	"checkout/package.json": {
		content: JSON.stringify({
			packageManager: "pnpm@9.0.0",
			scripts: { build: "true", test: "true", dev: "true" },
		}),
	},
	"checkout/go.mod": { content: "module example\n" },
	"checkout/Cargo.toml": { content: '[package]\nname = "x"\n' },
	"checkout/pom.xml": { content: "<project></project>\n" },
	"checkout/gradlew": { content: "#!/bin/sh\n" },
	"checkout/build.gradle.kts": { content: "\n" },
	"checkout/pyproject.toml": { content: '[project]\nname = "x"\n' },
	"checkout/uv.lock": { content: "\n" },
	"checkout/chart/Chart.yaml": { content: "name: checkout\n" },
};

const root = fs.mkdtempSync(path.join(os.tmpdir(), "devenv-discovery-"));
for (const [relative, file] of Object.entries(RECIPE)) {
	const full = path.join(root, relative);
	fs.mkdirSync(path.dirname(full), { recursive: true });
	fs.writeFileSync(full, file.content, { mode: file.mode ?? 0o644 });
}

const fixture: DiscoveryFixture = JSON.parse(
	fs
		.readFileSync(
			path.join(import.meta.dir, "fixtures", "actions", "discovery.json"),
			"utf8",
		)
		.replaceAll("{{ROOT}}", root),
);

/** Drops absent fields so both sides compare by value, not by key presence. */
function shape(target: ActionTarget | FixtureTarget): Record<string, unknown> {
	const out: Record<string, unknown> = {};
	for (const [key, value] of Object.entries(target)) {
		if (value === undefined || value === null) continue;
		if (Array.isArray(value) && value.length === 0) continue;
		out[key] = value;
	}
	return out;
}

describe("discovery", () => {
	for (const scenario of fixture.cases) {
		test(`${scenario.name} matches the targets Go discovered`, () => {
			const targets = discoverActionTargets({
				appIdent: scenario.appIdent,
				localDir: scenario.localDir,
				action: scenario.action,
				configDir: path.join(root, "config"),
				platform: "linux",
				// The fixture was captured where `pwsh` is installed, and the
				// resolver reads the host PATH. Pin it here; the installed-package
				// lookup itself is validated in `test/actions-scripts.test.ts`.
				powerShell: () => "pwsh",
			});
			expect(targets.map(shape)).toEqual(scenario.targets.map(shape));
		});
	}

	test("every captured scenario is exercised", () => {
		expect(fixture.cases.length).toBeGreaterThan(5);
		expect(new Set(fixture.cases.map((c) => c.action))).toEqual(
			new Set(["build", "test", "run"]),
		);
	});

	test("an unsupported action is rejected instead of returning nothing", () => {
		expect(() =>
			discoverActionTargets({
				appIdent: "shop",
				localDir: "",
				action: "deploy" as "run",
				configDir: path.join(root, "config"),
			}),
		).toThrow(/unsupported app action/);
	});
});

describe("target ordering", () => {
	test("targets sort by runtime, then by id", () => {
		const targets = discoverActionTargets({
			appIdent: "shop",
			localDir: path.join(root, "checkout"),
			action: "run",
			configDir: path.join(root, "config"),
			platform: "linux",
		});
		const keys = targets.map((t) => `${t.runtime}\u0000${t.id}`);
		expect(keys).toEqual([...keys].sort());
	});

	test("the same default compose file in both extensions yields both targets", () => {
		// Go matches `-compose.yml` and `-compose.yaml` as the default profile, so
		// a configured pair produces two targets with the same id. The fixture
		// records it and the port keeps it rather than de-duplicating silently.
		const targets = discoverActionTargets({
			appIdent: "shop",
			localDir: "",
			action: "run",
			configDir: path.join(root, "config"),
			platform: "linux",
		}).filter((t) => t.runtime === "docker");
		expect(targets).toHaveLength(3);
		expect(
			targets.filter((t) => t.id === "app/shop/run/docker/default"),
		).toHaveLength(2);
	});
});

describe("blocked and unrelated configuration", () => {
	test("another app's compose and run files are ignored", () => {
		const targets = discoverActionTargets({
			appIdent: "api",
			localDir: "",
			action: "run",
			configDir: path.join(root, "config"),
			platform: "linux",
		});
		expect(targets.map((t) => t.sourcePath)).not.toContain(
			path.join(root, "config", "apps", "compose", "other-compose.yml"),
		);
	});

	test("a build action without a checkout has no tooling targets", () => {
		const withCheckout = discoverActionTargets({
			appIdent: "shop",
			localDir: path.join(root, "checkout"),
			action: "build",
			configDir: path.join(root, "config"),
			platform: "linux",
		});
		const withoutCheckout = discoverActionTargets({
			appIdent: "shop",
			localDir: "",
			action: "build",
			configDir: path.join(root, "config"),
			platform: "linux",
		});
		expect(withoutCheckout.length).toBeLessThan(withCheckout.length);
		expect(
			withoutCheckout.every((t) =>
				t.sourcePath.includes("{{ROOT}}".replace("{{ROOT}}", "config")),
			),
		).toBe(true);
	});
});

describe("shell script metadata", () => {
	test("reads name, mode and requires from the header", () => {
		expect(
			parseShellScriptMetadata(
				path.join(root, "config", "apps", "run", "shop-dev.sh"),
				"logged",
			),
		).toEqual({
			name: "Dev server",
			mode: "tmux",
			requires: [{ app: "db", runtime: "docker", profile: "default" }],
		});
	});

	test("an empty or missing header keeps the default mode", () => {
		expect(
			parseShellScriptMetadata(
				path.join(root, "config", "apps", "run", "shop-api.sh"),
				"tmux",
			),
		).toEqual({ name: "", mode: "tmux", requires: [] });
		expect(
			parseShellScriptMetadata(path.join(root, "nope.sh"), "logged"),
		).toEqual({ name: "", mode: "logged", requires: [] });
	});

	test("the header ends at the first non-comment line", () => {
		const file = path.join(root, "late-header.sh");
		fs.writeFileSync(file, "#!/bin/sh\necho hi\n# devenv:name=Late\n", {
			mode: 0o755,
		});
		expect(parseShellScriptMetadata(file, "logged").name).toBe("");
	});

	test("a malformed requires header is reported with its source", () => {
		const file = path.join(root, "bad-header.sh");
		fs.writeFileSync(file, "# devenv:requires=not json\n", { mode: 0o755 });
		expect(() => parseShellScriptMetadata(file, "logged")).toThrow(
			/devenv:requires/,
		);
	});
});

describe("dependency references", () => {
	test("requires app or infra, never both, and app needs runtime and profile", () => {
		expect(() => parseDependencyRefs("[]", "test")).not.toThrow();
		expect(() => parseDependencyRefs('[{"infra":"db"}]', "test")).not.toThrow();
		expect(() =>
			parseDependencyRefs('[{"app":"db","infra":"x"}]', "test"),
		).toThrow(/cannot contain both app and infra/);
		expect(() => parseDependencyRefs('[{"app":"db"}]', "test")).toThrow(
			/requires runtime/,
		);
		expect(() =>
			parseDependencyRefs('[{"app":"db","runtime":"docker"}]', "test"),
		).toThrow(/requires profile/);
		expect(() =>
			parseDependencyRefs('[{"infra":"db","runtime":"shell"}]', "test"),
		).not.toThrow();
	});

	test("a compose x-devenv block must be inline JSON", () => {
		const file = path.join(root, "compose-nested.yml");
		fs.writeFileSync(file, "x-devenv:\n  requires:\n    - infra: db\n");
		expect(() => parseComposeRequires(file)).toThrow(/inline JSON array/);
	});

	test("a compose file without x-devenv has no dependencies", () => {
		expect(
			parseComposeRequires(
				path.join(root, "config", "apps", "compose", "shop-compose.yml"),
			),
		).toEqual([]);
		expect(parseComposeRequires(path.join(root, "missing.yml"))).toEqual([]);
	});
});

describe("kubernetes identity", () => {
	test("defaults provider, cluster and context", () => {
		expect(
			applyKubernetesIdentity(undefined, undefined, undefined, ""),
		).toEqual({
			provider: "docker",
			cluster: "devenv",
			context: "kind-devenv",
		});
		expect(
			applyKubernetesIdentity(undefined, undefined, undefined, "staging"),
		).toEqual({
			provider: "docker",
			cluster: "devenv-staging",
			context: "kind-devenv-staging",
		});
		expect(
			applyKubernetesIdentity("podman", "shop-cluster", undefined, "staging"),
		).toEqual({
			provider: "podman",
			cluster: "shop-cluster",
			context: "kind-shop-cluster",
		});
	});

	test("chart discovery and profiles follow the Go rules", () => {
		const charts = discoverHelmCharts(path.join(root, "checkout"));
		expect(charts).toEqual([path.join(root, "checkout", "chart")]);
		expect(
			kubernetesProfileForChart(path.join(root, "checkout", "chart")),
		).toBe("local");
		expect(kubernetesProfileForChart("/x/shop-chart")).toBe("shop");
		expect(kubernetesProfileForChart("/x/helm")).toBe("local");
		expect(kubernetesProfileForChart(".")).toBe("local");
	});

	test("a release defaults to the app ident for the local profile", () => {
		expect(defaultKubernetesRelease("shop", "")).toBe("shop");
		expect(defaultKubernetesRelease("shop", "local")).toBe("shop");
		expect(defaultKubernetesRelease("shop", "edge")).toBe("shop-edge");
	});

	test("$APP and $CONFIG expand, then relative paths resolve against the config file", () => {
		expect(
			expandKubernetesPath(
				"$APP/helm",
				"/apps/shop",
				"/config",
				"/config/apps",
			),
		).toBe("/apps/shop/helm");
		expect(
			expandKubernetesPath(
				"$CONFIG/values.yaml",
				"/apps/shop",
				"/config",
				"/x",
			),
		).toBe("/config/values.yaml");
		expect(expandKubernetesPath("chart", "/apps/shop", "/config", "/x/y")).toBe(
			path.normalize("/x/y/chart"),
		);
		expect(expandKubernetesPath("", "/a", "/c", "/b")).toBe("");
	});
});

describe("package manager selection", () => {
	test("the declared packageManager wins", () => {
		const dir = path.join(root, "checkout");
		expect(packageManagerCommand(dir, "build")).toEqual([
			"pnpm",
			["run", "build"],
		]);
	});

	test("yarn omits the run subcommand", () => {
		const dir = path.join(root, "yarn-app");
		fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(
			path.join(dir, "package.json"),
			JSON.stringify({ packageManager: "yarn@4.0.0" }),
		);
		expect(packageManagerCommand(dir, "dev")).toEqual(["yarn", ["dev"]]);
	});

	test("a lockfile decides when the field is absent", () => {
		const dir = path.join(root, "bun-app");
		fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(path.join(dir, "package.json"), "{}");
		fs.writeFileSync(path.join(dir, "bun.lockb"), "");
		expect(packageManagerCommand(dir, "dev")).toEqual(["bun", ["run", "dev"]]);
	});

	test("npm is the fallback", () => {
		const dir = path.join(root, "npm-app");
		fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(path.join(dir, "package.json"), "{}");
		expect(packageManagerCommand(dir, "dev")).toEqual(["npm", ["run", "dev"]]);
	});
});

describe("fixture coverage", () => {
	test("the fixture exercises every runtime", () => {
		const runtimes = new Set(
			fixture.cases.flatMap((c) => c.targets.map((t) => t.runtime)),
		);
		expect(runtimes).toEqual(
			new Set(["docker", "shell", "powershell", "systemshell", "kubernetes"]),
		);
	});
});
