// Stable environment-action identity (`port-action-execution-to-bun`,
// task 1.2).
//
// `test/fixtures/actions/target-ids.json` and the `stableIds` section of
// `definitions.json` are generated by the Go implementation
// (`server/pkg/resources/fixtures_test.go`,
// `server/pkg/actionregistry/fixtures_test.go`), so these assertions are parity
// against the compiler rather than a restatement of the port. The compiled
// definitions themselves — every id, kind, label, port and configuration — are
// asserted in `actions-definitions.test.ts`.
import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import path from "node:path";
import {
	actionTargetId,
	nestedStepId,
	resourceActionId,
	stableId,
	stepId,
} from "../src/server/actions/identity.ts";

interface TargetIdCase {
	ident: string;
	action: string;
	runtime: string;
	profile?: string;
	value: string;
}
interface StableIdCase {
	parts: string[];
	value: string;
}
interface DefinitionFixture {
	stableIds: StableIdCase[];
}

const FIXTURES = path.join(import.meta.dir, "fixtures", "actions");
const targetIds: TargetIdCase[] = JSON.parse(
	fs.readFileSync(path.join(FIXTURES, "target-ids.json"), "utf8"),
);
const definitions: DefinitionFixture = JSON.parse(
	fs.readFileSync(path.join(FIXTURES, "definitions.json"), "utf8"),
);

describe("stableId", () => {
	test("matches the Go composition for every captured part set", () => {
		for (const c of definitions.stableIds) {
			expect(stableId(...c.parts)).toBe(c.value);
		}
	});

	test("trims slashes and drops empty parts", () => {
		expect(stableId("/app/api/", "//step//")).toBe("app/api/step");
		expect(stableId("app", "", "  ", "action")).toBe("app/action");
		expect(stableId()).toBe("");
		expect(stableId("single")).toBe("single");
	});
});

describe("actionTargetId", () => {
	test("matches the Go builder, including profile-less and app-less forms", () => {
		for (const c of targetIds) {
			expect(
				actionTargetId(c.ident, c.action, c.runtime, c.profile ?? ""),
			).toBe(c.value);
		}
	});

	test("covers both the app-scoped and the app-less shape", () => {
		expect(targetIds.some((c) => c.ident === "")).toBe(true);
		expect(
			targetIds.some((c) => c.ident !== "" && c.profile === undefined),
		).toBe(true);
	});
});

describe("id builders reproduce the compiled identity", () => {
	test("resourceActionId composes `<kind>/<id>/action/<action>/<runtime>/<profile>`", () => {
		expect(resourceActionId("app", "api", "run", "docker", "dev")).toBe(
			"app/api/action/run/docker/dev",
		);
		expect(resourceActionId("app", "api", "pull", "git")).toBe(
			"app/api/action/pull/git/default",
		);
		expect(resourceActionId("infra", "postgres", "stop", "script")).toBe(
			"infra/postgres/action/stop/script/default",
		);
		expect(resourceActionId("kubernetes", "local", "create", "docker")).toBe(
			"kubernetes/local/action/create/docker/default",
		);
	});

	test("stepId and nestedStepId extend an action or step id", () => {
		expect(stepId("app/api/action/pull/git/default", "root")).toBe(
			"app/api/action/pull/git/default/step/root",
		);
		expect(
			stepId(
				"app/api/action/run/docker/dev",
				"dependency",
				"0",
				"app/db/run/docker",
			),
		).toBe("app/api/action/run/docker/dev/step/dependency/0/app/db/run/docker");
		expect(nestedStepId("step-1", "readiness")).toBe("step-1/readiness");
	});
});
