// Script discovery, mutation, interpreter selection and shell-action scripts
// (`port-action-execution-to-bun`, tasks 3.1, 3.2 and 3.4).
//
// `test/fixtures/actions/scripts.json` is generated by
// `server/pkg/resources/scripts_fixtures_test.go` from a materialized recipe
// tree (executable bits, shebangs, nested folders). Every path in it is a
// `{{ROOT}}` recipe key, so the test rebuilds the same tree in its own temp root
// and replays the recorded outcomes — including the failure diagnostics.
import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
	createScriptFile,
	DEFAULT_NEW_SCRIPT_TEMPLATE,
	deleteScriptTarget,
	discoverScripts,
	isRecognizedInterpreter,
	linkScriptFile,
	mapShebangToWindows,
	readInterpreterFromShebang,
	readShebang,
	resolveScriptTargetPath,
	scriptsDir,
	validateExistingScriptPath,
	windowsExtInterpreterMap,
	writeShellActionScript,
} from "../src/server/actions/scripts.ts";

interface DiscoveredFile {
	name: string;
	relativePath: string;
	absolutePath: string;
	directory: string;
	extension: string;
	interpreter?: string;
}
interface TargetPathCase {
	targetPath: string;
	defaultExtension: string;
	relativePath?: string;
	absolutePath?: string;
	error?: string;
}
interface SourcePathCase {
	sourcePath: string;
	error?: string;
}
interface MutationCase {
	operation: "create" | "link" | "delete";
	targetPath: string;
	sourcePath?: string;
	content?: string;
	relativePath?: string;
	absolutePath?: string;
	error?: string;
	written?: string;
	isLink?: boolean;
}
interface ShellActionCase {
	name: string;
	ident: string;
	action: string;
	profile: string;
	command: string;
	runtime: string;
	path?: string;
	error?: string;
	written?: string;
}
interface ShebangCase {
	relativePath: string;
	interpreter?: string;
	args?: string[];
	resolvedInterpreter?: string;
}
interface ScriptFixture {
	discovered: DiscoveredFile[];
	missingDir: DiscoveredFile[];
	targetPaths: TargetPathCase[];
	sourcePaths: SourcePathCase[];
	mutations: MutationCase[];
	shellActions: ShellActionCase[];
	interpreters: {
		shebangs: ShebangCase[];
		windowsMapping: { name: string; mapped: string }[];
		windowsExt: Record<string, string>;
		recognized: { name: string; recognized: boolean }[];
	};
}

/** The recipe both fixtures were captured against. */
const RECIPE: Record<string, { content: string; mode: number }> = {
	"deploy.sh": { content: "#!/usr/bin/env bash\nset -eu\n", mode: 0o755 },
	"nested/run.sh": { content: "#!/bin/sh\necho run\n", mode: 0o755 },
	"nested/deep/task.ps1": { content: "Write-Host task\n", mode: 0o755 },
	"tools/report.py": {
		content: "#!/usr/bin/env python3\nprint(1)\n",
		mode: 0o755,
	},
	"tools/bundle.js": { content: "console.log(1)\n", mode: 0o755 },
	"tools/not-executable.sh": { content: "#!/bin/sh\necho nope\n", mode: 0o644 },
	"tools/plain-executable": { content: "just text\n", mode: 0o755 },
	"tools/secret.sh": { content: "#!/usr/bin/env zsh\n", mode: 0o755 },
};

const root = fs.mkdtempSync(path.join(os.tmpdir(), "devenv-scripts-"));
for (const [relative, file] of Object.entries(RECIPE)) {
	const full = path.join(root, "home", "scripts", relative);
	fs.mkdirSync(path.dirname(full), { recursive: true });
	fs.writeFileSync(full, file.content, { mode: file.mode });
}
fs.writeFileSync(
	path.join(root, "home", "external.sh"),
	"#!/usr/bin/env sh\necho external\n",
	{ mode: 0o755 },
);

const raw = fs.readFileSync(
	path.join(import.meta.dir, "fixtures", "actions", "scripts.json"),
	"utf8",
);
const fixture: ScriptFixture = JSON.parse(raw.replaceAll("{{ROOT}}", root));
const scriptsDirectory = scriptsDir(path.join(root, "home"));

describe("discovery", () => {
	test("finds exactly the Go-discovered scripts, sorted by relative path", () => {
		const discovered = discoverScripts(scriptsDirectory, { platform: "linux" });
		expect(
			discovered.map((s) => ({
				relativePath: s.relativePath,
				extension: s.extension,
				...(s.interpreter ? { interpreter: s.interpreter } : {}),
			})),
		).toEqual(
			fixture.discovered.map((s) => ({
				relativePath: s.relativePath,
				extension: s.extension,
				...(s.interpreter ? { interpreter: s.interpreter } : {}),
			})),
		);
	});

	test("records the absolute path and directory for each script", () => {
		const discovered = discoverScripts(scriptsDirectory, { platform: "linux" });
		expect(discovered.map((s) => [s.absolutePath, s.directory])).toEqual(
			fixture.discovered.map((s) => [s.absolutePath, s.directory]),
		);
	});

	test("skips non-executable files and honours the executable bit", () => {
		const discovered = discoverScripts(scriptsDirectory, { platform: "linux" });
		const paths = discovered.map((s) => s.relativePath);
		expect(paths).not.toContain("tools/not-executable.sh");
		expect(paths).toContain("tools/plain-executable");
	});

	test("an empty or missing directory yields no scripts and no error", () => {
		expect(discoverScripts("", { platform: "linux" })).toEqual([]);
		expect(
			discoverScripts(path.join(root, "no-such-dir"), { platform: "linux" }),
		).toEqual(fixture.missingDir);
	});

	test("windows discovery falls back to shebang and extension", () => {
		const discovered = discoverScripts(scriptsDirectory, { platform: "win32" });
		const paths = discovered.map((s) => s.relativePath);
		// A non-executable file with a recognized extension is still a script on
		// Windows; an executable file with no shebang and no extension is not.
		expect(paths).toContain("tools/not-executable.sh");
		expect(paths).not.toContain("tools/plain-executable");
	});
});

describe("interpreter selection", () => {
	test("reads the shebang interpreter and its arguments", () => {
		for (const expectation of fixture.interpreters.shebangs) {
			const script = path.join(scriptsDirectory, expectation.relativePath);
			const { interpreter, args } = readShebang(script);
			expect(interpreter).toBe(expectation.interpreter ?? "");
			expect(args).toEqual(expectation.args ?? []);
			expect(
				readInterpreterFromShebang(script, path.extname(script).toLowerCase()),
			).toBe(expectation.resolvedInterpreter ?? "");
		}
	});

	test("falls back to the extension when there is no shebang", () => {
		expect(
			readInterpreterFromShebang(
				path.join(scriptsDirectory, "tools/bundle.js"),
				".js",
			),
		).toBe("bun");
		expect(
			readInterpreterFromShebang(
				path.join(scriptsDirectory, "tools/plain-executable"),
				"",
			),
		).toBe("");
	});

	test("reads a shebang with arguments and an env indirection", () => {
		const file = path.join(root, "shebangs");
		fs.writeFileSync(file, "#!/usr/bin/env -S python3 -u\n", { mode: 0o755 });
		const { interpreter, args } = readShebang(file);
		// `env` takes the next field as the interpreter, as Go does.
		expect(interpreter).toBe("-S");
		expect(args).toEqual(["python3", "-u"]);
	});

	test("maps unix interpreter names to their Windows executables", () => {
		for (const c of fixture.interpreters.windowsMapping) {
			expect(mapShebangToWindows(c.name)).toBe(c.mapped);
		}
	});

	test("keeps Go's extension and recognition tables", () => {
		const extensions = windowsExtInterpreterMap();
		for (const [extension, interpreter] of Object.entries(
			fixture.interpreters.windowsExt,
		)) {
			expect(extensions[extension]).toBe(interpreter);
		}
		for (const c of fixture.interpreters.recognized) {
			expect(isRecognizedInterpreter(c.name)).toBe(c.recognized);
		}
	});
});

describe("target paths", () => {
	test("matches Go for every accepted and rejected target", () => {
		for (const c of fixture.targetPaths) {
			if (c.error !== undefined) {
				expect(() =>
					resolveScriptTargetPath(
						scriptsDirectory,
						c.targetPath,
						c.defaultExtension,
					),
				).toThrow(c.error);
				continue;
			}
			expect(
				resolveScriptTargetPath(
					scriptsDirectory,
					c.targetPath,
					c.defaultExtension,
				),
			).toEqual({
				relativePath: c.relativePath ?? "",
				absolutePath: c.absolutePath ?? "",
			});
		}
	});

	test("never escapes the scripts directory", () => {
		for (const target of [
			"../escape",
			"..",
			"/absolute",
			"a/../../escape",
			"nested/../../escape",
		]) {
			expect(() =>
				resolveScriptTargetPath(scriptsDirectory, target, ".sh"),
			).toThrow(/escape scripts\/|must be relative/);
		}
	});

	test("an unconfigured scripts directory is rejected", () => {
		expect(() => resolveScriptTargetPath("  ", "x", ".sh")).toThrow(
			"scripts directory is not configured",
		);
	});
});

describe("source paths", () => {
	test("matches Go for files, directories, missing paths and no extension", () => {
		for (const c of fixture.sourcePaths) {
			const source = c.sourcePath.replace(/^$/, "");
			if (c.error !== undefined) {
				expect(() => validateExistingScriptPath(source)).toThrow(c.error);
				continue;
			}
			expect(validateExistingScriptPath(source).extension).toBe(".sh");
		}
	});
});

describe("mutations", () => {
	test("replays create, link and delete with Go's outcomes", () => {
		for (const c of fixture.mutations) {
			const run = () => {
				if (c.operation === "create") {
					return createScriptFile(
						scriptsDirectory,
						c.targetPath,
						c.content ?? "",
					);
				}
				if (c.operation === "link") {
					return linkScriptFile(
						scriptsDirectory,
						c.targetPath,
						c.sourcePath ?? "",
					);
				}
				return deleteScriptTarget(scriptsDirectory, c.targetPath);
			};
			if (c.error !== undefined) {
				expect(run).toThrow(c.error);
				continue;
			}
			const result = run();
			expect(result.relativePath).toBe(c.relativePath ?? "");
			expect(result.absolutePath).toBe(c.absolutePath ?? "");
			if (c.written !== undefined) {
				expect(fs.readFileSync(result.absolutePath, "utf8")).toBe(c.written);
			}
			if (c.isLink) {
				expect(fs.lstatSync(result.absolutePath).isSymbolicLink()).toBe(true);
			}
		}
	});

	test("a created script is executable and a deletion removes a folder tree", () => {
		const created = createScriptFile(
			scriptsDirectory,
			"fresh/one",
			DEFAULT_NEW_SCRIPT_TEMPLATE,
		);
		expect(fs.statSync(created.absolutePath).mode & 0o111).not.toBe(0);
		const removed = deleteScriptTarget(scriptsDirectory, "fresh");
		expect(fs.existsSync(removed.absolutePath)).toBe(false);
	});
});

describe("shell action scripts", () => {
	test("matches the Go path, mode header and content", () => {
		for (const c of fixture.shellActions) {
			const request = {
				appIdent: c.ident,
				action: c.action,
				profile: c.profile,
				command: c.command,
				extension: (c.runtime === "powershell" ? ".ps1" : ".sh") as
					| ".sh"
					| ".ps1",
			};
			if (c.error !== undefined) {
				expect(() =>
					writeShellActionScript(path.join(root, "config"), request),
				).toThrow(c.error);
				continue;
			}
			const written = writeShellActionScript(
				path.join(root, "config"),
				request,
			);
			expect(written).toBe(c.path ?? "");
			expect(fs.readFileSync(written, "utf8")).toBe(c.written ?? "");
		}
	});

	test("a run action is tmux and profile-scoped, a build action is logged", () => {
		const configDir = path.join(root, "modeconfig");
		const run = writeShellActionScript(configDir, {
			appIdent: "api",
			action: "run",
			profile: "dev",
			command: "npm run dev",
			extension: ".sh",
		});
		expect(fs.readFileSync(run, "utf8")).toContain("# devenv:mode=tmux");
		expect(path.basename(run)).toBe("api-dev.sh");
		expect(path.dirname(run)).toBe(path.join(configDir, "apps", "run"));

		const build = writeShellActionScript(configDir, {
			appIdent: "api",
			action: "build",
			profile: "ignored",
			command: "",
			extension: ".sh",
		});
		expect(fs.readFileSync(build, "utf8")).toContain("# devenv:mode=logged");
		expect(fs.readFileSync(build, "utf8")).toContain(
			"TODO: replace with your command",
		);
		expect(path.basename(build)).toBe("api-build.sh");
	});
});

describe("fixture coverage", () => {
	test("every section is populated", () => {
		expect(fixture.discovered.length).toBeGreaterThan(5);
		expect(fixture.targetPaths.length).toBeGreaterThan(8);
		expect(fixture.mutations.length).toBeGreaterThan(6);
		expect(fixture.shellActions.length).toBeGreaterThan(4);
		expect(
			fixture.targetPaths.filter((c) => c.error !== undefined).length,
		).toBeGreaterThan(3);
		expect(
			fixture.mutations.filter((c) => c.error !== undefined).length,
		).toBeGreaterThan(3);
	});
});
