// Canonical step labels and command classification
// (`port-action-execution-to-bun`, task 1.2).
//
// `test/fixtures/actions/labels.json` is generated by
// `server/pkg/actionrun/fixtures_test.go` from the Go implementation, so these
// assertions are parity, not a restatement of the port.
import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import path from "node:path";
import {
	actionKind,
	commandStepKind,
	decodeStepKind,
	encodeStepKind,
	gitCommandStepKind,
	stepLabel,
	titleCaseCommand,
} from "../src/server/actions/labels.ts";

interface LabelCase {
	kind: string;
	args?: string[];
	fallback: string;
	label: string;
	defect?: string;
	note?: string;
}
interface GitKindCase {
	args: string;
	kind: string;
}
interface CommandKindCase {
	operation: string;
	command: string;
	args: string[];
	kind: string;
	label: string;
}
interface ActionKindCase {
	action: string;
	kind: string;
}
interface LabelFixture {
	stepLabels: LabelCase[];
	gitCommandKinds: GitKindCase[];
	commandKinds: CommandKindCase[];
	actionKinds: ActionKindCase[];
	encoded: LabelCase[];
}

const fixture: LabelFixture = JSON.parse(
	fs.readFileSync(
		path.join(import.meta.dir, "fixtures", "actions", "labels.json"),
		"utf8",
	),
);

describe("step label registry", () => {
	test("resolves every captured Go label", () => {
		for (const c of fixture.stepLabels) {
			if (c.defect) continue;
			expect(stepLabel(c.kind, c.fallback)).toBe(c.label);
		}
	});

	test("documents the one deliberate divergence from Go", () => {
		const defects = fixture.stepLabels.filter((c) => c.defect);
		expect(defects.length).toBe(1);
		const defect = defects[0];
		if (!defect) throw new Error("missing defect fixture");
		// Go renders fmt's `%!s(MISSING)` for a templated kind reached without
		// its args; Bun substitutes nothing. The Go value stays in the fixture
		// so the divergence cannot drift unnoticed.
		expect(defect.label).toBe("Create secret %!s(MISSING)");
		expect(stepLabel(defect.kind, defect.fallback)).toBe("Create secret ");
	});

	test("resolves most captured cases through the registry, not the fallback", () => {
		// A fixture that only exercised the title-case fallback would pass even
		// with an empty registry.
		const viaRegistry = fixture.stepLabels.filter(
			(c) => !c.defect && c.label !== titleCaseCommand(c.fallback),
		);
		expect(viaRegistry.length).toBeGreaterThanOrEqual(30);
	});
});

describe("step kind encoding", () => {
	test("round-trips encoded kinds", () => {
		for (const c of fixture.encoded) {
			const decoded = decodeStepKind(c.kind);
			expect(decoded.kind).toBe(c.label);
			expect(decoded.args).toEqual(c.args ?? []);
		}
	});

	test("encodeStepKind leaves a kind without args untouched", () => {
		expect(encodeStepKind("git.fetch")).toBe("git.fetch");
		expect(encodeStepKind("kubernetes.secret.delete", "db")).toBe(
			"kubernetes.secret.delete|db",
		);
		expect(encodeStepKind("port-forward", "web", "8080")).toBe(
			"port-forward|web|8080",
		);
	});
});

describe("git command classification", () => {
	test("classifies by verb, not position", () => {
		for (const c of fixture.gitCommandKinds) {
			expect(gitCommandStepKind(c.args)).toBe(c.kind);
		}
	});
});

describe("process command classification", () => {
	test("matches Go for compose, kind, helm and operation fallbacks", () => {
		for (const c of fixture.commandKinds) {
			expect(commandStepKind(c.operation, c.command, c.args)).toBe(c.kind);
			expect(stepLabel(c.kind, c.command)).toBe(c.label);
		}
	});
});

describe("action kind bucket", () => {
	test("matches Go for every captured action key", () => {
		for (const c of fixture.actionKinds) {
			expect(actionKind(c.action)).toBe(c.kind);
		}
	});
});

describe("titleCaseCommand", () => {
	test("keeps only the first letter of each word uppercased", () => {
		expect(titleCaseCommand("git symbolic-ref HEAD")).toBe(
			"Git Symbolic-ref HEAD",
		);
		expect(titleCaseCommand("   ")).toBe("Command");
		expect(titleCaseCommand("helm   list")).toBe("Helm List");
	});
});
