// Script tree, metadata discovery, bounded probing and process-tree
// cancellation (`port-action-execution-to-bun`, tasks 3.1, 3.2, 3.3 and 3.5).
//
// `test/fixtures/actions/script-server.json` is generated by
// `server/pkg/server/scripts_fixtures_test.go` (tree, metadata parsing and the
// unix execution plan). The windows plan path switches on the *runtime*
// platform in Go, so it is asserted here against a stubbed platform with the
// interpreter mapping already pinned by `actions-scripts.test.ts`.
import { describe, expect, test } from "bun:test";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { MemoryProcessStore } from "../src/server/actions/process.ts";
import {
	collectProcessTree,
	killProcessTree,
	windowsKillTreeCommand,
} from "../src/server/actions/process-group.ts";
import {
	buildScriptTree,
	discoverScripts,
	fetchScriptMetadata,
	METADATA_WORKERS,
	mapBounded,
	parseMetadataOutput,
	parseShellScriptMetadata,
	resolveScriptExecutionPlan,
	ScriptMetadataCache,
	type ScriptParameter,
	writeShellActionScript,
} from "../src/server/actions/scripts.ts";

interface TreeCase {
	name: string;
	relativePath: string;
	absolutePath: string;
	nodeType: string;
	interpreter?: string;
	children?: TreeCase[];
}
interface MetadataCase {
	name: string;
	output: string;
	params: ScriptParameter[];
}
interface PlanCase {
	name: string;
	scriptPath: string;
	extraArgs: string[];
	goos: string;
	availableInterpreter?: string[];
	command?: string;
	args?: string[];
	workingDir?: string;
	error?: string;
}
interface ServerFixture {
	metadata: MetadataCase[];
	plans: PlanCase[];
	tree: TreeCase[];
}

const RECIPE: Record<string, { content: string; mode: number }> = {
	"deploy.sh": { content: "#!/usr/bin/env bash\n", mode: 0o755 },
	"nested/run.sh": { content: "#!/bin/sh\n", mode: 0o755 },
	"nested/deep/task.ps1": { content: "Write-Host task\n", mode: 0o755 },
	"tools/report.py": { content: "#!/usr/bin/env python3\n", mode: 0o755 },
	"tools/bundle.js": { content: "console.log(1)\n", mode: 0o755 },
	"tools/not-executable.sh": { content: "#!/bin/sh\n", mode: 0o644 },
	"tools/plain-executable": { content: "just text\n", mode: 0o755 },
};

const root = fs.mkdtempSync(path.join(os.tmpdir(), "devenv-script-server-"));
for (const [relative, file] of Object.entries(RECIPE)) {
	const full = path.join(root, "home", "scripts", relative);
	fs.mkdirSync(path.dirname(full), { recursive: true });
	fs.writeFileSync(full, file.content, { mode: file.mode });
}

const fixture: ServerFixture = JSON.parse(
	fs
		.readFileSync(
			path.join(import.meta.dir, "fixtures", "actions", "script-server.json"),
			"utf8",
		)
		.replaceAll("{{ROOT}}", root),
);
const scriptsDirectory = path.join(root, "home", "scripts");

function projectTree(node: TreeCase): Record<string, unknown> {
	return {
		name: node.name,
		relativePath: node.relativePath,
		absolutePath: node.absolutePath,
		nodeType: node.nodeType,
		...(node.interpreter !== undefined
			? { interpreter: node.interpreter }
			: {}),
		...(node.children ? { children: node.children.map(projectTree) } : {}),
	};
}

describe("script tree", () => {
	test("matches the Go folder/script tree", () => {
		const tree = buildScriptTree(
			discoverScripts(scriptsDirectory, { platform: "linux" }),
		);
		expect(tree.map(projectTree)).toEqual(fixture.tree.map(projectTree));
	});

	test("folders sort before scripts and both sort by name", () => {
		const tree = buildScriptTree(
			discoverScripts(scriptsDirectory, { platform: "linux" }),
		);
		expect(tree.map((node) => [node.nodeType, node.name])).toEqual([
			["folder", "nested"],
			["folder", "tools"],
			["script", "deploy.sh"],
		]);
	});

	test("an empty tree is an empty list, never a placeholder node", () => {
		expect(buildScriptTree([])).toEqual([]);
	});
});

describe("metadata parsing", () => {
	test("matches Go for arrays, envelopes, a single parameter and garbage", () => {
		for (const c of fixture.metadata) {
			expect(parseMetadataOutput(c.output)).toEqual(c.params);
		}
	});

	test("an unrecognized payload yields no parameters instead of throwing", () => {
		expect(parseMetadataOutput("not json")).toEqual([]);
		expect(parseMetadataOutput("")).toEqual([]);
		expect(parseMetadataOutput("null")).toEqual([]);
		expect(parseMetadataOutput("[1,2,3]")).toEqual([]);
		expect(parseMetadataOutput('{"other":1}')).toEqual([]);
	});
});

describe("execution plan", () => {
	test("matches the captured unix plan", () => {
		for (const c of fixture.plans) {
			const script = {
				name: path.basename(c.scriptPath),
				relativePath: path.basename(c.scriptPath),
				absolutePath: c.scriptPath,
				directory: path.dirname(c.scriptPath),
				extension: path.extname(c.scriptPath).toLowerCase(),
			};
			const plan = resolveScriptExecutionPlan(script, c.extraArgs, {
				platform: c.goos,
				lookPath: (name) =>
					(c.availableInterpreter ?? []).includes(name) ? name : undefined,
			});
			expect(plan.command).toBe(c.command ?? "");
			expect(plan.args).toEqual(c.args ?? []);
			expect(plan.workingDir).toBe(c.workingDir ?? "");
		}
	});

	test("windows resolves the interpreter and requires it to be present", () => {
		const script = path.join(scriptsDirectory, "nested/deep/task.ps1");
		const plan = resolveScriptExecutionPlan(
			{
				name: "task.ps1",
				relativePath: "nested/deep/task.ps1",
				absolutePath: script,
				directory: path.dirname(script),
				extension: ".ps1",
			},
			["-X"],
			{
				platform: "win32",
				lookPath: (name) => (name === "pwsh" ? name : undefined),
			},
		);
		expect(plan.command).toBe("pwsh");
		expect(plan.args).toEqual([script, "-X"]);
	});

	test("an unavailable interpreter fails before execution", () => {
		const script = path.join(scriptsDirectory, "nested/deep/task.ps1");
		expect(() =>
			resolveScriptExecutionPlan(
				{
					name: "task.ps1",
					relativePath: "nested/deep/task.ps1",
					absolutePath: script,
					directory: path.dirname(script),
					extension: ".ps1",
				},
				[],
				{ platform: "win32", lookPath: () => undefined },
			),
		).toThrow(/interpreter "pwsh" not available/);
	});
});

describe("metadata discovery", () => {
	test("uses --devenv-metadata and caches by path and mtime", async () => {
		const script = path.join(scriptsDirectory, "deploy.sh");
		const cache = new ScriptMetadataCache();
		const calls: string[][] = [];
		const spawn = async (command: string[]): Promise<string> => {
			calls.push(command);
			return `[{"name":"env","type":"string","required":true}]`;
		};
		const first = await fetchScriptMetadata(script, { cache, spawn });
		expect(calls[0]).toEqual([script, "--devenv-metadata"]);
		expect(first).toHaveLength(1);

		// A second read while the file is unchanged is served from the cache.
		const second = await fetchScriptMetadata(script, { cache, spawn });
		expect(second).toEqual(first);
		expect(calls).toHaveLength(1);

		// Touching the file invalidates it.
		const future = new Date(Date.now() + 5_000);
		fs.utimesSync(script, future, future);
		await fetchScriptMetadata(script, { cache, spawn });
		expect(calls).toHaveLength(2);
	});

	test("an unavailable script is not cached and yields no parameters", async () => {
		const cache = new ScriptMetadataCache();
		const parameters = await fetchScriptMetadata(
			path.join(root, "missing.sh"),
			{ cache, spawn: async () => "" },
		);
		expect(parameters).toEqual([]);
	});

	test("a probe that overruns its deadline has its process tree killed", async () => {
		const script = path.join(root, "slow.sh");
		fs.writeFileSync(script, "#!/bin/sh\nsleep 30 &\nsleep 30\n", {
			mode: 0o755,
		});
		const started = Date.now();
		const parameters = await fetchScriptMetadata(script, { timeoutMs: 150 });
		expect(parameters).toEqual([]);
		expect(Date.now() - started).toBeLessThan(5000);
	});
});

describe("bounded probing", () => {
	test("preserves input order while limiting concurrency", async () => {
		let inFlight = 0;
		let peak = 0;
		const results = await mapBounded(
			[1, 2, 3, 4, 5, 6, 7],
			3,
			async (value) => {
				inFlight++;
				peak = Math.max(peak, inFlight);
				await Bun.sleep(5);
				inFlight--;
				return value * 2;
			},
		);
		expect(results).toEqual([2, 4, 6, 8, 10, 12, 14]);
		expect(peak).toBeLessThanOrEqual(3);
	});

	test("a large script collection is probed with a bounded pool", async () => {
		let inFlight = 0;
		let peak = 0;
		await mapBounded(
			Array.from({ length: 40 }, (_, i) => i),
			METADATA_WORKERS,
			async () => {
				inFlight++;
				peak = Math.max(peak, inFlight);
				await Bun.sleep(1);
				inFlight--;
				return null;
			},
		);
		expect(peak).toBeLessThanOrEqual(METADATA_WORKERS);
	});

	test("an empty collection resolves without probing", async () => {
		let calls = 0;
		expect(
			await mapBounded([], METADATA_WORKERS, async () => {
				calls++;
				return 0;
			}),
		).toEqual([]);
		expect(calls).toBe(0);
	});
});

describe("launch mode metadata", () => {
	test("reads the name and tmux mode a shell action script declares", () => {
		const configDir = path.join(root, "launch");
		const script = writeShellActionScript(configDir, {
			appIdent: "api",
			action: "run",
			profile: "dev-server",
			command: "npm run dev",
			extension: ".sh",
		});
		expect(parseShellScriptMetadata(script, "logged")).toEqual({
			name: "dev-server",
			mode: "tmux",
		});
	});

	test("a missing header keeps the default mode", () => {
		const plain = path.join(root, "plain.sh");
		fs.writeFileSync(plain, "#!/bin/sh\necho hi\n", { mode: 0o755 });
		expect(parseShellScriptMetadata(plain, "tmux")).toEqual({
			name: "",
			mode: "tmux",
		});
	});

	test("an unknown mode is ignored, a missing file is not an error", () => {
		const odd = path.join(root, "odd.sh");
		fs.writeFileSync(odd, "# devenv:name=x\n# devenv:mode=sideways\n", {
			mode: 0o755,
		});
		expect(parseShellScriptMetadata(odd, "logged")).toEqual({
			name: "x",
			mode: "logged",
		});
		expect(
			parseShellScriptMetadata(path.join(root, "nope.sh"), "logged"),
		).toEqual({ name: "", mode: "logged" });
	});
});

describe("process tree cancellation", () => {
	test("orders descendants deepest first and the root last", () => {
		const table = [
			"  10   1",
			"  11  10",
			"  12  11",
			"  13  10",
			"  99   1",
		].join("\n");
		expect(collectProcessTree(10, () => table)).toEqual([12, 11, 13, 10]);
	});

	test("an unreadable process table falls back to the direct child", () => {
		expect(collectProcessTree(10, () => undefined)).toBeUndefined();
	});

	test("windows terminates the tree with taskkill", () => {
		expect(windowsKillTreeCommand(42)).toEqual([
			"taskkill",
			"/PID",
			"42",
			"/T",
			"/F",
		]);
		const ran: string[][] = [];
		killProcessTree(42, {
			platform: "win32",
			runWindows: (command) => ran.push(command),
		});
		expect(ran).toEqual([["taskkill", "/PID", "42", "/T", "/F"]]);
	});

	test("a cancelled wrapper takes its children with it", async () => {
		// A shell that starts a background child and then waits: killing only the
		// wrapper would leave the child running.
		const marker = path.join(root, "child-alive.txt");
		const proc = Bun.spawn(
			[
				"sh",
				"-c",
				`sh -c 'sleep 30; echo done > ${marker}' & echo $! > ${root}/child.pid; wait`,
			],
			{ stdout: "ignore", stderr: "ignore" },
		);
		await Bun.sleep(200);
		const childPid = Number(
			fs.readFileSync(path.join(root, "child.pid"), "utf8").trim(),
		);
		expect(childPid).toBeGreaterThan(0);
		killProcessTree(proc.pid, { signal: "SIGKILL" });
		await Bun.sleep(300);
		expect(isAlive(proc.pid)).toBe(false);
		expect(isAlive(childPid)).toBe(false);
	});

	test("an adopted process is not killed by another run's cancellation", async () => {
		const store = new MemoryProcessStore();
		const adopted = Bun.spawn(["sh", "-c", "sleep 30"], {
			stdout: "ignore",
			stderr: "ignore",
		});
		store.put("adopted", {
			mode: "process",
			pid: adopted.pid,
			startedAt: new Date().toISOString(),
		});
		const owned = Bun.spawn(["sh", "-c", "sleep 30"], {
			stdout: "ignore",
			stderr: "ignore",
		});
		killProcessTree(owned.pid, { signal: "SIGKILL" });
		await Bun.sleep(200);
		expect(isAlive(owned.pid)).toBe(false);
		// The adopted resource belongs to a different owner and survives.
		expect(isAlive(adopted.pid)).toBe(true);
		store.killAll();
		await Bun.sleep(200);
		expect(isAlive(adopted.pid)).toBe(false);
	});

	test("killing an already-exited process is not an error", () => {
		const proc = Bun.spawnSync(["sh", "-c", "true"]);
		expect(() => killProcessTree(proc.pid)).not.toThrow();
		expect(() => killProcessTree(0)).not.toThrow();
		expect(() => killProcessTree(-1)).not.toThrow();
	});
});

function isAlive(pid: number): boolean {
	try {
		process.kill(pid, 0);
		return true;
	} catch {
		return false;
	}
}
