import { expect, test } from 'bun:test';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { registerBuiltins } from '../src/workflow/definitions.ts';
import type { ResolvedProfile, WorkflowRouting, WorkflowView } from '../src/workflow/contracts.ts';
import { WorkflowEngine } from '../src/workflow/runtime.ts';

const profile: ResolvedProfile = { name: 'fake', runtime: 'pi', executable: process.execPath, tools: [], extensions: [], readOnly: false, capabilities: ['prompt', 'run-environment', 'observe'], digest: 'fake' };
const routing: WorkflowRouting = { defaultProfile: 'fake', routes: ['core.plan', 'core.implementation', 'core.triage', 'core.verification', 'core.archive'].map(stepId => ({ stepId, profile })), diversity: [] };
function repo(): string { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'e2e-')); execFileSync('git', ['init', '-q', '-b', 'main'], { cwd: root }); fs.mkdirSync(path.join(root, 'openspec')); fs.writeFileSync(path.join(root, 'openspec', 'config.yaml'), 'schema: spec-driven\n'); execFileSync('git', ['add', '.'], { cwd: root }); execFileSync('git', ['-c', 'user.email=test@example.com', '-c', 'user.name=Test', 'commit', '-qm', 'base'], { cwd: root }); return root }
function launchToken(engine: WorkflowEngine, root: string, runId: string): string { const effect = engine.claimEffects(root, 100).find(item => item.kind === 'agent.launch' && (item.payload as { runId?: string }).runId === runId); if (!effect?.runToken) throw new Error(`missing launch token for ${runId}`); return effect.runToken }
function complete(engine: WorkflowEngine, root: string, view: WorkflowView, role: string, payload: unknown): WorkflowView { const summary = view.runs.find(run => run.role === role && ['pending', 'working'].includes(run.status)); if (!summary) throw new Error(`missing ${role} run`); const run = engine.getRun(root, summary.id); const token = launchToken(engine, root, run.id); fs.mkdirSync(path.dirname(run.outputPath!), { recursive: true }); fs.writeFileSync(run.outputPath!, JSON.stringify({ runId: run.id, schemaId: run.outputSchema!.id, schemaVersion: run.outputSchema!.version, payload })); return engine.dispatch(root, { type: 'agent.handoff', runId: run.id, generation: run.generation, token, outcome: 'complete', artifact: run.outputPath }).view }
function action(engine: WorkflowEngine, root: string, view: WorkflowView, actionId: string): WorkflowView { return engine.dispatch(root, { type: 'developer.action', workflowId: view.workflowId, revision: view.revision, actionId }).view }
function drive(engine: WorkflowEngine, root: string, definitionId: 'standard' | 'direct-apply' | 'no-openspec'): string[] {
  if (definitionId !== 'no-openspec') { const change = path.join(root, 'openspec', 'changes', definitionId); fs.mkdirSync(path.join(change, 'specs', 'feature'), { recursive: true }); fs.writeFileSync(path.join(change, 'proposal.md'), 'proposal\n'); fs.writeFileSync(path.join(change, 'design.md'), 'design\n'); fs.writeFileSync(path.join(change, 'tasks.md'), definitionId === 'direct-apply' ? '- [ ] task\n' : '- [x] task\n'); fs.writeFileSync(path.join(change, 'specs', 'feature', 'spec.md'), '#### Scenario: works\n'); execFileSync('git', ['add', '.'], { cwd: root }); execFileSync('git', ['-c', 'user.email=test@example.com', '-c', 'user.name=Test', 'commit', '-qm', 'plan'], { cwd: root }) }
  let view = engine.start({ repo: root, changeId: definitionId, definitionId, metadata: { branch: 'main', baseBranch: 'main', baseCommit: 'base', ...(definitionId === 'no-openspec' ? { task: 'task' } : {}) }, routing }).view; const visited = [view.currentStep.id];
  if (definitionId === 'standard') { view = complete(engine, root, view, 'planner', { validated: true }); const validation = engine.claimEffects(root, 100).find(effect => effect.kind === 'openspec.validate')!; view = engine.dispatch(root, { type: 'effect.result', effectId: validation.id, lease: validation.lease!, outcome: 'complete' }).view; visited.push(view.currentStep.id); view = action(engine, root, view, 'approve-plan'); visited.push(view.currentStep.id) }
  if (definitionId === 'direct-apply') fs.writeFileSync(path.join(root, 'openspec', 'changes', definitionId, 'tasks.md'), '- [x] task\n');
  fs.writeFileSync(path.join(root, 'implementation.txt'), 'changed\n');
  view = complete(engine, root, view, 'worker', { changed: true }); visited.push(view.currentStep.id);
  view = complete(engine, root, view, 'triage', { roles: [{ role: 'quality-verifier', reason: 'code changed', files: ['implementation.txt'] }] }); visited.push(view.currentStep.id);
  view = complete(engine, root, view, 'quality-verifier', { findings: [] }); expect(view.currentStep.id).toBe('core.verification');
  view = complete(engine, root, view, 'test-verifier', { findings: [] }); visited.push(view.currentStep.id);
  view = action(engine, root, view, 'approve-review'); visited.push(view.currentStep.id);
  if (definitionId !== 'no-openspec') { const active = path.join(root, 'openspec', 'changes', definitionId); const archived = path.join(root, 'openspec', 'changes', 'archive', definitionId); fs.mkdirSync(path.dirname(archived), { recursive: true }); fs.renameSync(active, archived); view = complete(engine, root, view, 'archive', { archived: true }); visited.push(view.currentStep.id) }
  const commit = engine.claimEffects(root, 100).find(effect => effect.kind === 'delivery.commit')!; view = engine.dispatch(root, { type: 'effect.result', effectId: commit.id, lease: commit.lease!, outcome: 'complete' }).view;
  const push = engine.claimEffects(root, 100).find(effect => effect.kind === 'delivery.push')!; view = engine.dispatch(root, { type: 'effect.result', effectId: push.id, lease: push.lease!, outcome: 'complete' }).view; visited.push(view.currentStep.id);
  view = action(engine, root, view, 'close'); visited.push(view.currentStep.id); return visited;
}
for (const type of ['standard', 'direct-apply', 'no-openspec'] as const) test(`${type} definition reaches terminal through registered commands`, () => { const root = repo(); try { const sequence = drive(new WorkflowEngine(registerBuiltins()), root, type); expect(sequence.at(-1)).toBe('core.closed'); if (type === 'standard') expect(sequence[0]).toBe('core.plan'); else expect(sequence[0]).toBe('core.implementation'); expect(sequence.includes('core.archive')).toBe(type !== 'no-openspec') } finally { fs.rmSync(root, { recursive: true, force: true }) } });
test('review-comments request-changes dispatch validates bounded comment entries', () => { const root = repo(); try { const engine = new WorkflowEngine(registerBuiltins()); let view = engine.start({ repo: root, changeId: 'review-comments', definitionId: 'no-openspec', metadata: { branch: 'main', baseBranch: 'main', baseCommit: 'base', task: 'task' }, routing }).view; const worker = engine.getRun(root, view.runs.find(item => item.role === 'worker')!.id); let token = launchToken(engine, root, worker.id); fs.mkdirSync(path.dirname(worker.outputPath!), { recursive: true }); fs.writeFileSync(worker.outputPath!, JSON.stringify({ runId: worker.id, schemaId: worker.outputSchema!.id, schemaVersion: worker.outputSchema!.version, payload: { changed: true } })); view = engine.dispatch(root, { type: 'agent.handoff', runId: worker.id, generation: worker.generation, token, outcome: 'complete', artifact: worker.outputPath }).view; const triage = engine.getRun(root, view.runs.find(item => item.role === 'triage')!.id); token = launchToken(engine, root, triage.id); fs.mkdirSync(path.dirname(triage.outputPath!), { recursive: true }); fs.writeFileSync(triage.outputPath!, JSON.stringify({ runId: triage.id, schemaId: triage.outputSchema!.id, schemaVersion: triage.outputSchema!.version, payload: { roles: [] } })); view = engine.dispatch(root, { type: 'agent.handoff', runId: triage.id, generation: triage.generation, token, outcome: 'complete', artifact: triage.outputPath }).view; expect(view.currentStep.id).toBe('core.verification'); const tester = view.runs.find(item => item.role === 'test-verifier' && ['pending', 'working'].includes(item.status)); expect(tester).toBeTruthy(); const testRun = engine.getRun(root, tester!.id); token = launchToken(engine, root, testRun.id); fs.mkdirSync(path.dirname(testRun.outputPath!), { recursive: true }); fs.writeFileSync(testRun.outputPath!, JSON.stringify({ runId: testRun.id, schemaId: testRun.outputSchema!.id, schemaVersion: testRun.outputSchema!.version, payload: { findings: [] } })); view = engine.dispatch(root, { type: 'agent.handoff', runId: testRun.id, generation: testRun.generation, token, outcome: 'complete', artifact: testRun.outputPath }).view; expect(view.currentStep.id).toBe('core.developer-review'); expect(() => engine.dispatch(root, { type: 'developer.action', workflowId: view.workflowId, revision: view.revision, actionId: 'review-comments', input: { comments: [{ body: 'missing comment field' }] } })).toThrow(/invalid review comment/); const reported = engine.dispatch(root, { type: 'developer.action', workflowId: view.workflowId, revision: view.revision, actionId: 'review-comments', input: { comments: [{ comment: 'use const', file: 'a.ts', line: 2 }] } }).view; expect(reported.currentStep.id).toBe('core.implementation'); expect(engine.getSnapshot(root, reported.workflowId).step.mode).toBe('review-fix'); } finally { fs.rmSync(root, { recursive: true, force: true }) } });
